version: '3.9'

services:

  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=postgresql
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=1996
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
